INSERT INTO users (user_name, email, password) VALUES
('john_doe', 'john.doe@example.com', 'hashed_password_123'),
('jane_smith', 'jane.smith@example.com', 'hashed_password_456'),
('bob_wilson', 'bob.wilson@example.com', 'hashed_password_789'),
('alice_jones', 'alice.jones@example.com', 'hashed_password_abc'),
('charlie_brown', 'charlie.brown@example.com', 'hashed_password_def'),
('sarah_davis', 'sarah.davis@example.com', 'hashed_password_ghi'),
('mike_taylor', 'mike.taylor@example.com', 'hashed_password_jkl'),
('emma_white', 'emma.white@example.com', 'hashed_password_mno'),
('david_clark', 'david.clark@example.com', 'hashed_password_pqr'),
('lisa_martin', 'lisa.martin@example.com', 'hashed_password_stu');


INSERT INTO commodities (symbol, commodity_name, currency) VALUES
('DCUSD',  'Class III Milk Futures', 'USD'),
('RTYUSD', 'Micro E-mini Russell 2000 Index Futures', 'USD'),
('ZLUSX',  'Soybean Oil Futures', 'USX'),
('LEUSX',  'Live Cattle Futures', 'USX'),
('DXUSD',  'US Dollar', 'USD'),
('ZQUSD',  '30 Day Fed Fund Futures', 'USD'),
('ZFUSD',  'Five-Year US Treasury Note', 'USD'),
('HGUSD',  'Copper', 'USD'),
('ZSUSX',  'Soybean Futures', 'USX'),
('BZUSD',  'Brent Crude Oil', 'USD'),
('LBUSD',  'Lumber Futures', 'USD'),
('CLUSD',  'Crude Oil', 'USD'),
('ZMUSD',  'Soybean Meal Futures', 'USD'),
('ZCUSX',  'Corn Futures', 'USX'),
('YMUSD',  'Mini Dow Jones Industrial Average Index', 'USD'),
('ZTUSD',  '2-Year T-Note Futures', 'USD'),
('NGUSD',  'Natural Gas', 'USD'),
('GCUSD',  'Gold Futures', 'USD'),
('MGCUSD', 'Micro Gold Futures', 'USD'),
('SILUSD', 'Micro Silver Futures', 'USD'),
('ZOUSX',  'Oat Futures', 'USX'),
('NQUSD',  'Nasdaq 100', 'USD'),
('ALIUSD', 'Aluminum Futures', 'USD'),
('ESUSD',  'E-Mini S&P 500', 'USD'),
('CTUSX',  'Cotton', 'USX'),
('SBUSX',  'Sugar', 'USX'),
('PLUSD',  'Platinum', 'USD'),
('HOUSD',  'Heating Oil', 'USD'),
('OJUSX',  'Orange Juice', 'USX'),
('ZNUSD',  '10-Year T-Note Futures', 'USD'),
('PAUSD',  'Palladium', 'USD'),
('RBUSD',  'Gasoline RBOB', 'USD'),
('HEUSX',  'Lean Hogs Futures', 'USX'),
('KEUSX',  'Wheat Futures', 'USX'),
('ZBUSD',  '30 Year U.S. Treasury Bond Futures', 'USD'),
('CCUSD',  'Cocoa', 'USD'),
('ZRUSD',  'Rough Rice Futures', 'USD'),
('KCUSX',  'Coffee', 'USX'),
('GFUSX',  'Feeder Cattle Futures', 'USX'),
('SIUSD',  'Silver Futures', 'USD');